### ISSUE TITLE
when I do my first trial according to wikiHOWTO.md, an problem output.

### ISSUE THREAD

**Issue by xupeng1231** [vusec/vuzzer#11]
the following is my walkthrough，do you known the reason of the problem？

xupeng@ubuntu:~/vuzzerdir/vuzzer$  python runfuzzer.py -s '/home/xupeng/vuzzerdir/vuzzer/bin/who %s' -i 'datatemp/utmp/' -w 'idafiles/who.pkl' -n idafiles/who.names -o '0x00000000'
[*] Starting dry run now...
[*] Just about to run  ['/home/xupeng/vuzzerdir/pin2.14//pin', '-tool_exit_timeout', '1', '-t', '/home/xupeng/vuzzerdir/vuzzer/obj-ia32/bbcounts2.so', '-o', '/home/xupeng/vuzzerdir/vuzzer/outd/bbc.out', '-x', '0', '-libc', '0', '-l', '', '--', '/home/xupeng/vuzzerdir/vuzzer/bin/who', '/home/xupeng/vuzzerdir/vuzzer/datatemp/utmp/f2.utmp']
[*] Run complete..

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "runfuzzer.py", line 631, in main
    gbb,bbb=dry_run()
  File "runfuzzer.py", line 475, in dry_run
    (bbs,retc)=execute(tfl)
  File "runfuzzer.py", line 155, in execute
    bbs = bbdict(config.BBOUT)
  File "runfuzzer.py", line 77, in bbdict
    with open(config.BBOUT,"r") as bbFD:
IOError: [Errno 2] No such file or directory: '/home/xupeng/vuzzerdir/vuzzer/outd/bbc.out'

xupeng@ubuntu:~/vuzzerdir/vuzzer$

**Comment by tosanjay** [comment]
From the error, i can say that your pintool did not run. make sure that you have setup pin properly.
you can check this by running the following cmdline:/home/xupeng/vuzzerdir/pin2.14//pin -tool_exit_timeout 1 -t /home/xupeng/vuzzerdir/vuzzer/obj-ia32/bbcounts2.so -o /home/xupeng/vuzzerdir/vuzzer/outd/bbc.out -x 0 -libc 0 -l '' -- ./bin/who /home/xupeng/vuzzerdir/vuzzer/./datatemp/utmp/f2.utmp

This will show you the pintool error and you can fix that.

Thanks & Regards
- Sanjay

   On Wednesday, October 25, 2017, 5:20:55 PM GMT+2, xupeng1231 <notifications@github.com> wrote:  
 
 
the following is my walkthrough，do you known the reason of the problem？

xupeng@ubuntu:~/vuzzerdir/vuzzer$ python runfuzzer.py -s '/home/xupeng/vuzzerdir/vuzzer/bin/who %s' -i 'datatemp/utmp/' -w 'idafiles/who.pkl' -n idafiles/who.names -o '0x00000000'
[] Starting dry run now...
[] Just about to run ['/home/xupeng/vuzzerdir/pin2.14//pin', '-tool_exit_timeout', '1', '-t', '/home/xupeng/vuzzerdir/vuzzer/obj-ia32/bbcounts2.so', '-o', '/home/xupeng/vuzzerdir/vuzzer/outd/bbc.out', '-x', '0', '-libc', '0', '-l', '', '--', '/home/xupeng/vuzzerdir/vuzzer/bin/who', '/home/xupeng/vuzzerdir/vuzzer/datatemp/utmp/f2.utmp']
[*] Run complete..

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "runfuzzer.py", line 631, in main
gbb,bbb=dry_run()
File "runfuzzer.py", line 475, in dry_run
(bbs,retc)=execute(tfl)
File "runfuzzer.py", line 155, in execute
bbs = bbdict(config.BBOUT)
File "runfuzzer.py", line 77, in bbdict
with open(config.BBOUT,"r") as bbFD:
IOError: [Errno 2] No such file or directory: '/home/xupeng/vuzzerdir/vuzzer/outd/bbc.out'

xupeng@ubuntu:~/vuzzerdir/vuzzer$
