### ISSUE TITLE
About the Paper which issues in the NDSS'17

### ISSUE THREAD

**Issue by zlapluie** [vusec/vuzzer#16]
Hi, great work the Vuzzer.
When I read the paper published in the NDSS'17, the figure 2 which is a high-level CFG of the code shown in Listing 3 makes me a little confused. From the code you have given, the sentence 'if (buf[1]==0xEF && buf[0]==0xFD)' shown in the same block but the sentence 'if (buf[10]=='%' && buf[11]=='@')' shown in the different block - block E and F. And from the block E, one side is to check the word '@'. Does it mean that the check of the word '%' has passed. The other side goes to the block H. What does the 'some task' means? I couldn't find it in the code. And why the block F and G can go to the same error handle block? I couldn't correspond the figure with the code.
Thank you so mush for reading that.

**Comment by tosanjay** [comment]
HI,
thanks for your comments on VUzzer.
the CFG of Fig 2 is meant for showing the technique for calculating BB's weights. As a result, while it is based on the code shown in Listing 3, few extra nodes are also added to cover more code constructs. So you are right that not everything in this CFG corresponds to the code from Listing 3. To answer your specific questions: 
1. From the code you have given, the sentence 'if (buf[1]==0xEF && buf[0]==0xFD)' shown in the same block but the sentence 'if (buf[10]=='%' && buf[11]=='@')' shown in the different block - block E and F
>> yes, but it does not affect anything. In fact compiler can emit a code of this type. But as I said, the idea of this graph is to provide high-level view of the CFG to describe BB weight computation.
2.   And from the block E, one side is to check the word '@'. Does it mean that the check of the word '%' has passed.
>> Yes.

I hope this answers your questions. If so, please close the issue.

thanks
