### ISSUE TITLE
Error running BB-weight4.py

### ISSUE THREAD

**Issue by zhanggenex** [vusec/vuzzer#19]
I am trying to generate the names and pkl files of the binary with BB-weight4.py.
I got this error:

> Traceback (most recent call last):
>   File "fuzzer-code/BB-weight4.py", line 10, in <module>
>     import idaapi
> ImportError: No module named idaapi

Anyone konw how to do this?

I am a fresh in IDA. Thanks

**Comment by tosanjay** [comment]
I would suggest to use:
1. VUzzer64 repo and
2. Ghidra script that works with Ghidra , which is open source.
