### ISSUE TITLE
make libdft error

### ISSUE THREAD

**Issue by icepng** [vusec/vuzzer#2]
When I run this,
``` bash
make support-libdft
```
got a error
```
/vuzzer/pin/source/include/pin/foundation.PLH:52:26: fatal error: types_marker.h: No such file or directory
 #include "types_marker.h"
```
but I fount "types_marker.h" in the path   /vuzzer/pin/extras/crt/include

**Comment by vivek425ster** [comment]
Could you tell the version of pin which you are using ?

**Comment by tosanjay** [comment]
we tested it on pin 2.13, so, it is safe to use the same version.

**Comment by icepng** [comment]
i use pin-3.2 got that error, and pin-2.4 is ok.
but i got a new error when i tested the libxml2 make by myself.
```
rg@rg-virtual-machine:~/vuzzer$ python runfuzzer.py -s "/home/rg/vuzzer/bin/libxml2.so %s" -i 'datatemp/libxml2/' -w 'idafiles/libxml2.so.pkl' -n 'idafiles/libxml2.so.names' -o '0x00000000' 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "runfuzzer.py", line 623, in main
    gau.prepareBBOffsets()
  File "/home/rg/vuzzer/gautils.py", line 510, in prepareBBOffsets
    tBB=pickle.load(pFD)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by ner0x652** [comment]
@icepng @tosanjay Same happened to me.

**Comment by icepng** [comment]
i think i found the reason,  "It should be noted that with kernel 4.x.y, Pin (2.13) gets panic. ". @ner0x652

**Comment by tosanjay** [comment]
you are trying to run a shared lib, whereas -s takes the binary that will be executed by pin. so, try finding some utility that uses libxml2.so and then:
`vuzzer$ python runfuzzer.py -s "/home/rg/vuzzer/bin/your_exe %s" -i 'datatemp/libxml2/' -w 'idafiles/your_exe.pkl,idafiles/libxml2.so.pkl' -n 'idafiles/your_exe.names,idafiles/libxml2.so.names' -l 2 -o '0x00000000, 0xloadaddress_of_libxml2'`

**Comment by icepng** [comment]
if i write a program to test a shared lib, and i want to test the lib, is that means i should use much more APIs in the lib?

**Comment by ner0x652** [comment]
@icepng No, this issue is not related to the statement you quoted. I guess that header file was deprecated/removed... in later versions than Pin 2.13.

**Comment by icepng** [comment]
thx, which Ida version are you using for  plugin BB-weightv4, i got crash when used ida 6.6

**Comment by icepng** [comment]
i think this issue was solved, and i use pin2.14 and kernel 3.13

**Comment by tosanjay** [comment]
I see there is a mix of issues in single thread. if any of the mentioned issue is not resolved, please open a new issue again. I am closing this thread.

**Comment by apurvparekh30** [comment]
I am facing the issue with Pin 3.14 and linex kernel 4.10.0-33-generic. I made a dual ABI for gcc.
Please help

**Comment by pstegegn** [comment]
I am also having the same problem:

/home/pin-3.2-81205-gcc-linux/source/include/pin/foundation.PLH:52:26: fatal error: types_marker.h: No such file or directory

pin 3.14, kernel 4.10.0-28-generic, gcc 4.8

**Comment by feanorlecodeur** [comment]
Me too

**Comment by ThatsNotVeryCashMoneyOfYou** [comment]
Me too

**Comment by tosanjay** [comment]
Please note that pin 2.13-14 has problem with kernel 4.x. use kernel 3.x. see previous issues. More than that I would suggest to use VUzzer64.

 
 
  On Tue, Jun 25, 2019 at 21:09, Carson Harmon<notifications@github.com> wrote:   
Me too
