### ISSUE TITLE
Error on running 'who'

### ISSUE THREAD

**Issue by iceeeeee** [vusec/vuzzer#7]
Hi,

I cannot successfully run the command ` python runfuzzer.py -s '/PATH_TO_vuzzer-code/bin/who %s' -i 'datatemp/utmp/' -w 'idafiles/who.pkl' -n idafiles/who.names -o '0x00000000'`, which is provided in the wikiHOWTO.md.

The error is 

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "runfuzzer.py", line 631, in main
    gbb,bbb=dry_run()
  File "runfuzzer.py", line 475, in dry_run
    (bbs,retc)=execute(tfl)
  File "runfuzzer.py", line 155, in execute
    bbs = bbdict(config.BBOUT)
  File "runfuzzer.py", line 77, in bbdict
    with open(config.BBOUT,"r") as bbFD:
IOError: [Errno 2] No such file or directory: '/xxx/vuzzer/outd/bbc.out'

I think bbc.out should be an output file, so any hint on how this happen and how to fix it?

Thanks.

**Comment by tosanjay** [comment]
i my guess is: your pintool is not executing the application and therefore bbc.out is not getting generated. Just check if you can run pintool separately.

**Comment by iceeeeee** [comment]
@tosanjay Thanks for your quick reply. 

I tried the PIN, it is not executing because of the kernel version is too high. After I downgrade the kernel version, the PIN and the sample command could be successfully executed. 

However, I have the same problem when I run the program with library in it.  The following is the command I run. Another problem is that after run the command first time, get 'load address changed..run again!', the content of `imageOffset.text` is `Main: 0x00000000`, the library address is not in this file. There is an address `0xb6553000` in the file `image.offset`, so I use this address as the library address, I am not sure if this is correct.
```
python runfuzzer.py -s './bin/tiff2pdf %s -o result.pdf' \
 -i 'datatemp/tiff2pdftemp/' \
 -w './idafiles/tiff2pdf.pkl,./idafiles/libtiff.so.pkl' \
 -n './idafiles/tiff2pdf.names,./idafiles/libtiff.so.names' \
 -l 2 \
 -o '0x00000000, 0xb6553000' \
 -b 'tiff'
```

Thanks

**Comment by tosanjay** [comment]
As before, if pin is not able to run the application, it is difficult to move forward. can you run the application directly with pintool as follows:
$pin -tool_exit_timeout 1 -t pintool-path -o path-to-bbc.out -x 0 -libc 0-l "libtiff" -- your utility commandline

as you can see, i used lib name with full prefix. 
let me know what do you get.

**Comment by iceeeeee** [comment]
It works, thank you so much for your help. The pin command could work. After I change the lib name with full prefix, it fails on the first time I run it with the same error, success on the second time. 

During the runtime, vuzzer print out some error blocks. What are those error blocks? Would these error blocks have any influence on result?

**Comment by tosanjay** [comment]
Glad that it worked. for the other query on error BB, please read the VUzzer paper, presented at NDSS'17.
